/* VoltHub demo — seed data. All simulated. */

const CATS = [
  { id: 'batteries',  name: 'Batteries',             icon: 'battery',   blurb: 'Packs & cells' },
  { id: 'motors',     name: 'Motors',                icon: 'motor',     blurb: 'Hub & mid-drive' },
  { id: 'controllers',name: 'Controllers',           icon: 'chip',      blurb: 'Sine & FOC' },
  { id: 'displays',   name: 'Displays & Throttles',  icon: 'display',   blurb: 'LCD, throttles' },
  { id: 'brakes',     name: 'Brakes',                icon: 'brake',     blurb: 'Hydraulic & rotors' },
  { id: 'drivetrain', name: 'Drivetrain',            icon: 'gear',      blurb: 'Chains, belts, gears' },
  { id: 'wheels',     name: 'Wheels & Tires',        icon: 'wheel',     blurb: 'Rims, tires, tubes' },
  { id: 'suspension', name: 'Suspension & Frames',   icon: 'fork',      blurb: 'Forks, shocks' },
  { id: 'lights',     name: 'Lights & Electronics',  icon: 'light',     blurb: 'Lights, wiring' },
  { id: 'chargers',   name: 'Chargers',              icon: 'plug',      blurb: 'Fast & standard' },
  { id: 'security',   name: 'Locks & Security',      icon: 'lock',      blurb: 'Locks, GPS' },
  { id: 'accessories',name: 'Accessories & Tools',   icon: 'wrench',    blurb: 'Racks, torque arms' },
];

const BIKES = [
  { id: 'radrover6',  brand: 'Rad Power',   model: 'RadRover 6 Plus',   cls: 'Class 2' },
  { id: 'radrunner2', brand: 'Rad Power',   model: 'RadRunner 2',       cls: 'Class 2' },
  { id: 'xp30',       brand: 'Lectric',     model: 'XP 3.0',            cls: 'Class 3' },
  { id: 'xpeak',      brand: 'Lectric',     model: 'XPeak',             cls: 'Class 3' },
  { id: 'level2',     brand: 'Aventon',     model: 'Level.2',           cls: 'Class 3' },
  { id: 'aventure2',  brand: 'Aventon',     model: 'Aventure.2',        cls: 'Class 3' },
  { id: 'ride1up700', brand: 'Ride1Up',     model: '700 Series',        cls: 'Class 3' },
  { id: 'ripcurrent', brand: 'Juiced',      model: 'RipCurrent S',      cls: 'Class 3' },
  { id: 'vado4',      brand: 'Specialized', model: 'Turbo Vado 4.0',    cls: 'Class 3' },
  { id: 'allant7',    brand: 'Trek',        model: 'Allant+ 7',         cls: 'Class 3' },
  { id: 'super73z',   brand: 'Super73',     model: 'Z Miami',           cls: 'Class 2' },
  { id: 'maxg2',      brand: 'Segway',      model: 'Ninebot Max G2',    cls: 'Scooter' },
  { id: 'kqi3',       brand: 'Niu',         model: 'KQi3 Pro',          cls: 'Scooter' },
];

const SELLER_COLORS = {
  voltgarage: 'linear-gradient(135deg,#123a6b,#2f7ed8)',
  packworks:  'linear-gradient(135deg,#0ea48a,#19c8a8)',
  brakelab:   'linear-gradient(135deg,#141b23,#42566d)',
  radspares:  'linear-gradient(135deg,#b3541e,#e8a13c)',
  scootcity:  'linear-gradient(135deg,#155e75,#8ecdf7)',
  trailvolt:  'linear-gradient(135deg,#4a3fc0,#8f7ff0)',
};

function seedDB() {
  const now = Date.now(), day = 864e5;
  return {
    v: 1,
    session: null,
    users: [
      { id: 'u_buyer',  email: 'buyer@demo.com',  pw: btoa('demo1234'), name: 'Jordan Rivera', role: 'buyer',  wishlist: ['p_bbshd','p_pack52'], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_seller', email: 'seller@demo.com', pw: btoa('demo1234'), name: 'Sam Volt',      role: 'seller', sellerId: 's_voltgarage', wishlist: [], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_admin',  email: 'admin@demo.com',  pw: btoa('demo1234'), name: 'Mateo (Admin)', role: 'admin',  wishlist: [], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_s2', email: 'packworks@demo.com', pw: btoa('demo1234'), name: 'Priya Chen',   role: 'seller', sellerId: 's_packworks', wishlist: [], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_s3', email: 'brakelab@demo.com',  pw: btoa('demo1234'), name: 'Marcus Reed',  role: 'seller', sellerId: 's_brakelab',  wishlist: [], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_s4', email: 'radspares@demo.com', pw: btoa('demo1234'), name: 'Dana Ortiz',   role: 'seller', sellerId: 's_radspares', wishlist: [], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_s5', email: 'scootcity@demo.com', pw: btoa('demo1234'), name: 'Lee Nakamura', role: 'seller', sellerId: 's_scootcity', wishlist: [], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_s6', email: 'trailvolt@demo.com', pw: btoa('demo1234'), name: 'Casey Brooks', role: 'seller', sellerId: 's_trailvolt', wishlist: [], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_rev1', email: 'kim@demo.com',  pw: btoa('demo1234'), name: 'Kim Adebayo',  role: 'buyer', wishlist: [], cart: { items: [], codes: {} }, tos: true },
      { id: 'u_rev2', email: 'tyler@demo.com', pw: btoa('demo1234'), name: 'Tyler Moss',  role: 'buyer', wishlist: [], cart: { items: [], codes: {} }, tos: true },
    ],
    sellers: [
      { id: 's_voltgarage', userId: 'u_seller', slug: 'volt-garage', name: 'Volt Garage', color: SELLER_COLORS.voltgarage,
        tagline: 'Mid-drives, hub motors & controllers — bench-tested before they ship.',
        bio: 'Austin, TX shop specializing in Bafang and hub-motor builds since 2019. Every used unit is load-tested and photographed on the bench. Ask us about connector matching before you buy.',
        status: 'active', joined: now - 480 * day, verified: true },
      { id: 's_packworks', userId: 'u_s2', slug: 'packworks', name: 'PackWorks Battery Co', color: SELLER_COLORS.packworks,
        tagline: 'UL-listed packs, name-brand cells, honest capacity tests.',
        bio: 'We build and refurbish lithium packs with Samsung/LG/Molicel cells. Every pack ships with a printed capacity test and UN38.3 documentation. Ground shipping only, per DOT rules.',
        status: 'active', joined: now - 390 * day, verified: true },
      { id: 's_brakelab', userId: 'u_s3', slug: 'brakelab', name: 'BrakeLab', color: SELLER_COLORS.brakelab,
        tagline: 'Stopping power for heavy e-bikes. Hydraulics, rotors, pads.',
        bio: 'E-bikes are heavy and fast — your brakes should be boring and reliable. We stock Tektro, Magura and Shimano systems with cut-to-length lines.',
        status: 'active', joined: now - 300 * day, verified: true },
      { id: 's_radspares', userId: 'u_s4', slug: 'rad-spares', name: 'Rad Spares Co', color: SELLER_COLORS.radspares,
        tagline: 'OEM & takeoff parts for Rad Power bikes.',
        bio: 'Parting out Rad bikes so you don\'t have to. Fenders, racks, batteries, displays and controllers pulled from working bikes — photographed as-is.',
        status: 'active', joined: now - 220 * day, verified: true },
      { id: 's_scootcity', userId: 'u_s5', slug: 'scoot-city', name: 'ScootCity Parts', color: SELLER_COLORS.scootcity,
        tagline: 'Segway, Niu & Xiaomi scooter parts with same-day ship.',
        bio: 'Scooter commuters keep the city moving. Fenders, brake levers, tires and batteries for the big scooter brands, shipped from Chicago.',
        status: 'active', joined: now - 150 * day, verified: true },
      { id: 's_trailvolt', userId: 'u_s6', slug: 'trailvolt', name: 'TrailVolt Used', color: SELLER_COLORS.trailvolt,
        tagline: 'Budget used parts. Graded honestly, priced to move.',
        bio: 'Used and for-parts components from trail builds and teardowns. Read the condition notes — for-parts means for parts.',
        status: 'active', joined: now - 90 * day, verified: false },
    ],
    products: [
      // Volt Garage — motors & controllers
      { id: 'p_bbshd', sellerId: 's_voltgarage', title: 'Bafang BBSHD 1000W Mid-Drive Kit (68–73mm BB)', cat: 'motors', brand: 'Bafang', cond: 'new',
        price: 49900, ship: 1500, qty: 6, sold: 41, views: 1240, universal: true, fits: [],
        specs: { 'Power': '1000W nominal', 'Voltage': '48–52V', 'Bottom bracket': '68–73mm', 'Chainring': '46T included', 'Display': 'Not included' },
        desc: 'The workhorse mid-drive. Kit includes motor, controller (integrated), wiring harness, chainring and crank arms. Pair with a 52V pack for best throttle response. We flash the controller to legal defaults.', ts: now - 200 * day },
      { id: 'p_g062', sellerId: 's_voltgarage', title: 'Bafang G062 750W Rear Hub Motor — 26" laced', cat: 'motors', brand: 'Bafang', cond: 'like_new',
        price: 18900, ship: 2200, qty: 2, sold: 12, views: 640, universal: false, fits: ['radrover6','aventure2','ripcurrent'],
        specs: { 'Power': '750W nominal', 'Freehub': '7-speed', 'Dropout': '175mm', 'Rim': '26" double-wall', 'Cable': '9-pin Julet' },
        desc: 'Takeoff from a 200-mile build. Laced into a 26" double-wall rim, trued on the stand. 9-pin Julet connector — check your harness.', ts: now - 90 * day },
      { id: 'p_kt35', sellerId: 's_voltgarage', title: 'KT 35A Sine Wave Controller 48V', cat: 'controllers', brand: 'KT', cond: 'new',
        price: 7900, ship: 900, qty: 14, sold: 33, views: 890, universal: true, fits: [],
        specs: { 'Current': '35A max', 'Voltage': '48V', 'Type': 'Sine wave', 'Display': 'KT-LCD series', 'Phase wires': '12 AWG' },
        desc: 'Silent sine-wave controller, plug-and-play with KT displays. Supports torque-sim PAS and thumb throttle.', ts: now - 150 * day },
      { id: 'p_sabvoton', sellerId: 's_voltgarage', title: 'Sabvoton SVMC72050 72V 50A Controller (used)', cat: 'controllers', brand: 'Sabvoton', cond: 'used',
        price: 14500, ship: 1200, qty: 1, sold: 3, views: 410, universal: true, fits: [],
        specs: { 'Current': '50A cont.', 'Voltage': '72V max', 'Type': 'FOC', 'Bluetooth': 'Yes (app tune)', 'Condition note': 'Bench-tested, scuffed case' },
        desc: 'FOC controller for high-power hub builds. App-tunable. Cosmetic scuffs, electrically perfect — see bench video on request.', ts: now - 30 * day },
      { id: 'p_860c', sellerId: 's_voltgarage', title: 'Bafang 860C Color Display', cat: 'displays', brand: 'Bafang', cond: 'new',
        price: 8900, ship: 700, qty: 9, sold: 18, views: 520, universal: false, fits: ['radrover6','radrunner2','aventure2'],
        specs: { 'Screen': '3.2" IPS color', 'Protocol': 'UART (Bafang)', 'Connector': '5-pin Higo', 'USB': '5V 1A out' },
        desc: 'Crisp color display for BBS and Bafang hub systems. 5-pin Higo — verify your harness before ordering.', ts: now - 120 * day },
      // PackWorks — batteries & chargers
      { id: 'p_pack52', sellerId: 's_packworks', title: '52V 17.5Ah Battery — Samsung 50E cells, UL 2271', cat: 'batteries', brand: 'PackWorks', cond: 'new',
        price: 42900, ship: 0, qty: 8, sold: 57, views: 2100, universal: true, fits: [],
        specs: { 'Voltage': '52V (58.8V full)', 'Capacity': '17.5Ah / 910Wh', 'Cells': 'Samsung 50E', 'BMS': '30A continuous', 'Discharge plug': 'XT60', 'Certification': 'UL 2271, UN38.3' },
        desc: 'Our best-selling pack. Genuine Samsung 50E cells, smart 30A BMS, capacity test printout included. Free ground shipping (batteries never ship air).', ts: now - 260 * day },
      { id: 'p_pack48rad', sellerId: 's_packworks', title: '48V 14Ah Rad-Compatible Downtube Pack', cat: 'batteries', brand: 'PackWorks', cond: 'new',
        price: 33900, ship: 0, qty: 5, sold: 24, views: 1150, universal: false, fits: ['radrover6','radrunner2'],
        specs: { 'Voltage': '48V', 'Capacity': '14Ah / 672Wh', 'Cells': 'LG M50LT', 'Mount': 'Rad downtube rail', 'Certification': 'UN38.3' },
        desc: 'Drop-in replacement for Rad downtube packs, keyed mount included. Fits RadRover 6 and RadRunner 2 rails.', ts: now - 180 * day },
      { id: 'p_charger52', sellerId: 's_packworks', title: '58.8V 5A Fast Charger (52V systems, XLR)', cat: 'chargers', brand: 'PackWorks', cond: 'new',
        price: 8900, ship: 800, qty: 20, sold: 31, views: 760, universal: true, fits: [],
        specs: { 'Output': '58.8V 5A', 'For packs': '52V nominal', 'Plug': '3-pin XLR', 'Fan': 'Temp-controlled' },
        desc: '0–100% in under 4 hours on a 17.5Ah pack. Auto-cutoff at 58.8V. XLR plug standard.', ts: now - 140 * day },
      { id: 'p_maxbat', sellerId: 's_scootcity', title: 'Segway Max External Battery Kit 36V 7.8Ah', cat: 'batteries', brand: 'Segway', cond: 'like_new',
        price: 19900, ship: 0, qty: 3, sold: 9, views: 480, universal: false, fits: ['maxg2'],
        specs: { 'Voltage': '36V', 'Capacity': '7.8Ah', 'Mount': 'Stem bracket incl.', 'Certification': 'UN38.3' },
        desc: 'Range extender kit pulled from a display unit. Charged 4 times. Doubles the G2\'s usable range.', ts: now - 45 * day },
      // BrakeLab
      { id: 'p_tektro', sellerId: 's_brakelab', title: 'Tektro HD-E350 Hydraulic E-Bike Brake Set (pair)', cat: 'brakes', brand: 'Tektro', cond: 'new',
        price: 11900, ship: 1000, qty: 12, sold: 46, views: 1320, universal: true, fits: [],
        specs: { 'Type': 'Hydraulic, 2-piston', 'Cutoff': 'E-bike sensor incl.', 'Levers': 'Alloy, 3-finger', 'Hose': 'Pre-bled, cut-to-length' },
        desc: 'The standard upgrade from mechanical discs on commuter e-bikes. Motor-cutoff sensors included, pre-bled.', ts: now - 210 * day },
      { id: 'p_rotors', sellerId: 's_brakelab', title: '203mm Rotors 6-Bolt (pair) — heavy e-bike rated', cat: 'brakes', brand: 'BrakeLab', cond: 'new',
        price: 3900, ship: 600, qty: 30, sold: 28, views: 610, universal: true, fits: [],
        specs: { 'Diameter': '203mm', 'Mount': '6-bolt', 'Thickness': '2.0mm', 'Rated': 'Cargo/fat e-bikes' },
        desc: 'Bigger rotors, cooler brakes. 2.0mm plate resists warp on long descents with heavy bikes.', ts: now - 100 * day },
      { id: 'p_mt5e', sellerId: 's_brakelab', title: 'Magura MT5e 4-Piston Brake (single, HIGO cutoff)', cat: 'brakes', brand: 'Magura', cond: 'new',
        price: 18900, ship: 900, qty: 4, sold: 11, views: 540, universal: true, fits: [],
        specs: { 'Type': 'Hydraulic, 4-piston', 'Cutoff': 'HIGO opener', 'Rated': '45 km/h class', 'Side': 'Left or right (set at checkout note)' },
        desc: 'The heavy-cargo standard. One lever+caliper unit with HIGO cutoff switch for speed-pedelec builds.', ts: now - 75 * day },
      // Drivetrain / wheels / suspension
      { id: 'p_gates', sellerId: 's_voltgarage', title: 'Gates CDX Belt Drive Kit 122T (Bosch/Brose IGH)', cat: 'drivetrain', brand: 'Gates', cond: 'new',
        price: 24600, ship: 900, qty: 3, sold: 7, views: 390, universal: false, fits: ['vado4','allant7'],
        specs: { 'Belt': 'CDX 122T carbon', 'Front': '50T CDX', 'Rear': '24T CDX (HG spline)', 'For': 'IGH/belt-ready frames only' },
        desc: 'Silent, greaseless, 20k-mile drivetrain. Frame must have a belt splitter — check before ordering.', ts: now - 60 * day },
      { id: 'p_cues', sellerId: 's_trailvolt', title: 'Shimano CUES U6000 9sp Derailleur (takeoff)', cat: 'drivetrain', brand: 'Shimano', cond: 'like_new',
        price: 6400, ship: 700, qty: 2, sold: 5, views: 260, universal: true, fits: [],
        specs: { 'Speeds': '9', 'Cage': 'Medium', 'Max cog': '46T', 'Mileage': '~50 miles' },
        desc: 'Takeoff from a new bike converted to IGH. Basically new, tiny cable rub mark.', ts: now - 25 * day },
      { id: 'p_kenda', sellerId: 's_radspares', title: 'Kenda Krusade 20×4.0 Fat Tire + Tube', cat: 'wheels', brand: 'Kenda', cond: 'new',
        price: 5200, ship: 1100, qty: 10, sold: 22, views: 700, universal: false, fits: ['radrunner2','xp30','super73z'],
        specs: { 'Size': '20×4.0"', 'Bead': 'Wire', 'Tread': 'Street/mixed', 'Tube': '20×4 Schrader incl.' },
        desc: 'The RadRunner/Lectric street tire. Tube included — swap both, your future self says thanks.', ts: now - 130 * day },
      { id: 'p_wheel275', sellerId: 's_trailvolt', title: '27.5" Rear Wheel, 148 Boost, HG Freehub (used)', cat: 'wheels', brand: 'WTB', cond: 'used',
        price: 8900, ship: 1800, qty: 1, sold: 2, views: 190, universal: false, fits: ['aventure2','level2'],
        specs: { 'Size': '27.5"', 'Spacing': '148×12 Boost', 'Freehub': 'Shimano HG', 'Condition note': 'True, brake track worn' },
        desc: 'Solid spare wheel. Bearings smooth, rim true within 0.5mm. Sold as pictured.', ts: now - 20 * day },
      { id: 'p_fork35', sellerId: 's_trailvolt', title: 'RockShox 35 Silver TK 120mm 29" Fork', cat: 'suspension', brand: 'RockShox', cond: 'used',
        price: 29900, ship: 2000, qty: 1, sold: 1, views: 340, universal: false, fits: ['aventure2','vado4'],
        specs: { 'Travel': '120mm', 'Wheel': '29"', 'Steerer': 'Tapered, 190mm', 'Axle': '15×110 Boost', 'Condition note': 'Stanchions clean, lowers scuffed' },
        desc: 'Coil fork with turnkey lockout, ideal e-bike commuter upgrade. Fresh lower service 100 miles ago.', ts: now - 15 * day },
      { id: 'p_thud', sellerId: 's_radspares', title: 'Cane Creek Thudbuster ST Suspension Seatpost 31.6', cat: 'suspension', brand: 'Cane Creek', cond: 'like_new',
        price: 13900, ship: 900, qty: 2, sold: 6, views: 410, universal: true, fits: [],
        specs: { 'Diameter': '31.6mm', 'Travel': '50mm', 'Elastomer': 'Medium installed', 'Rider max': '330 lb' },
        desc: 'The cheapest comfort upgrade for a hardtail e-bike. Takeoff, ridden one season.', ts: now - 55 * day },
      // Lights, security, accessories, scooter
      { id: 'p_lezyne', sellerId: 's_brakelab', title: 'Lezyne Ebike Power HB StVZO Headlight (12V feed)', cat: 'lights', brand: 'Lezyne', cond: 'new',
        price: 7500, ship: 600, qty: 7, sold: 8, views: 300, universal: true, fits: [],
        specs: { 'Input': '6–12V from controller', 'Output': '310 lux StVZO', 'Mount': '31.8/35mm bar' },
        desc: 'Wire it to the controller\'s light feed — no charging, ever. Cutoff beam won\'t blind traffic.', ts: now - 85 * day },
      { id: 'p_krypto', sellerId: 's_scootcity', title: 'Kryptonite New-U Evolution U-Lock + Cable', cat: 'security', brand: 'Kryptonite', cond: 'new',
        price: 7900, ship: 900, qty: 15, sold: 19, views: 520, universal: true, fits: [],
        specs: { 'Shackle': '14mm hardened', 'Rating': 'Sold Secure Gold', 'Cable': '4ft flex incl.' },
        desc: 'The baseline city lock. Register the key code. No lock stops a grinder — park smart.', ts: now - 110 * day },
      { id: 'p_torque', sellerId: 's_voltgarage', title: 'Torque Arm V4 — Stainless (hub motor must-have)', cat: 'accessories', brand: 'Grin', cond: 'new',
        price: 2900, ship: 500, qty: 25, sold: 37, views: 830, universal: true, fits: [],
        specs: { 'Material': '304 stainless', 'Fits': '10mm flatted axles', 'Side': 'Universal' },
        desc: 'Cheap insurance: keeps a powerful hub motor from spinning out of aluminum dropouts. Buy two.', ts: now - 170 * day },
      { id: 'p_radplate', sellerId: 's_radspares', title: 'Rad Battery Mounting Plate + Keys (takeoff)', cat: 'accessories', brand: 'Rad Power', cond: 'used',
        price: 4500, ship: 800, qty: 3, sold: 4, views: 210, universal: false, fits: ['radrover6','radrunner2'],
        specs: { 'Includes': 'Rail, lock core, 2 keys', 'Pulled from': '2023 RadRover 6' },
        desc: 'Working lock core with both keys. Swap your worn rail or build a second battery mount.', ts: now - 40 * day },
      { id: 'p_g2fender', sellerId: 's_scootcity', title: 'Ninebot Max G2 Front Fender OEM', cat: 'accessories', brand: 'Segway', cond: 'new',
        price: 2400, ship: 600, qty: 18, sold: 13, views: 350, universal: false, fits: ['maxg2'],
        specs: { 'Fitment': 'Max G2 only', 'Color': 'Black', 'Hardware': 'Screws incl.' },
        desc: 'OEM replacement fender. Ten-minute install with a T15.', ts: now - 70 * day },
      { id: 'p_kqilever', sellerId: 's_scootcity', title: 'Niu KQi3 Brake Lever Assembly (left)', cat: 'brakes', brand: 'Niu', cond: 'new',
        price: 2500, ship: 500, qty: 11, sold: 7, views: 240, universal: false, fits: ['kqi3'],
        specs: { 'Side': 'Left', 'Sensor': 'Cutoff switch incl.', 'Fitment': 'KQi3 Pro/Sport' },
        desc: 'Direct replacement lever with integrated cutoff. Plug-and-play on KQi3 Pro and Sport.', ts: now - 35 * day },
      { id: 'p_surron', sellerId: 's_trailvolt', title: 'Full-Suspension E-Moto Frame (Sur-Ron style, for parts)', cat: 'suspension', brand: 'Unbranded', cond: 'for_parts',
        price: 55000, ship: 8000, qty: 1, sold: 0, views: 620, universal: true, fits: [],
        specs: { 'Style': 'LBX-pattern', 'Includes': 'Frame, swingarm, linkage', 'Condition note': 'Cracked headtube gusset — WELD REPAIR REQUIRED' },
        desc: 'Sold strictly for parts/repair. Cracked gusset shown in photos. Great donor for a rebuild project if you can weld.', ts: now - 10 * day },
      { id: 'p_xp3battery', sellerId: 's_radspares', title: 'Lectric XP 3.0 48V 10.4Ah Battery (tested 96% cap)', cat: 'batteries', brand: 'Lectric', cond: 'used',
        price: 21900, ship: 0, qty: 1, sold: 1, views: 450, universal: false, fits: ['xp30'],
        specs: { 'Voltage': '48V', 'Capacity': '10.4Ah (tested 9.98Ah)', 'Cycles': '~60 est.', 'Certification': 'OEM pack, UN38.3' },
        desc: 'Pulled from a low-mile XP 3.0. Capacity test photo in gallery. Ground ship only.', ts: now - 18 * day },
    ],
    codes: [
      { id: 'c_volt10',  sellerId: 's_voltgarage', code: 'VOLT10',  type: 'percent', value: 10, min: 0,     max: 100, uses: 23, expires: null, active: true },
      { id: 'c_pack15',  sellerId: 's_packworks',  code: 'PACK15',  type: 'fixed',   value: 1500, min: 20000, max: 50, uses: 12, expires: null, active: true },
      { id: 'c_brake5',  sellerId: 's_brakelab',   code: 'BRAKE5',  type: 'fixed',   value: 500,  min: 0,     max: null, uses: 31, expires: null, active: true },
      { id: 'c_scoot10', sellerId: 's_scootcity',  code: 'SCOOT10', type: 'percent', value: 10, min: 3000,  max: 200, uses: 4, expires: null, active: true },
      { id: 'c_trail20', sellerId: 's_trailvolt',  code: 'TRAIL20', type: 'percent', value: 20, min: 0,     max: 10, uses: 10, expires: now - 5 * day, active: true },
    ],
    orders: [
      { id: 'o_1001', groupId: 'g_501', buyerId: 'u_buyer', sellerId: 's_packworks',
        items: [{ pid: 'p_pack52', title: '52V 17.5Ah Battery — Samsung 50E cells, UL 2271', price: 42900, qty: 1 }],
        subtotal: 42900, discount: 1500, codeId: 'c_pack15', shipping: 0, total: 41400, fee: 4140,
        status: 'delivered', tracking: 'UPS 1Z999AA10123456784', ts: now - 21 * day, shippedTs: now - 19 * day, deliveredTs: now - 15 * day,
        address: { name: 'Jordan Rivera', line1: '482 Cedar Loop', city: 'Austin', state: 'TX', zip: '78745' } },
      { id: 'o_1002', groupId: 'g_502', buyerId: 'u_buyer', sellerId: 's_voltgarage',
        items: [{ pid: 'p_torque', title: 'Torque Arm V4 — Stainless (hub motor must-have)', price: 2900, qty: 2 }],
        subtotal: 5800, discount: 0, codeId: null, shipping: 1000, total: 6800, fee: 580,
        status: 'shipped', tracking: 'USPS 9400 1000 0000 0000 0000 01', ts: now - 4 * day, shippedTs: now - 2 * day, deliveredTs: null,
        address: { name: 'Jordan Rivera', line1: '482 Cedar Loop', city: 'Austin', state: 'TX', zip: '78745' } },
      { id: 'o_1003', groupId: 'g_503', buyerId: 'u_rev1', sellerId: 's_voltgarage',
        items: [{ pid: 'p_kt35', title: 'KT 35A Sine Wave Controller 48V', price: 7900, qty: 1 }],
        subtotal: 7900, discount: 0, codeId: null, shipping: 900, total: 8800, fee: 790,
        status: 'paid', tracking: null, ts: now - 1 * day, shippedTs: null, deliveredTs: null,
        address: { name: 'Kim Adebayo', line1: '77 Marina Way', city: 'Oakland', state: 'CA', zip: '94607' } },
    ],
    reviews: [
      { id: 'r1', orderId: 'o_9001', sellerId: 's_packworks', buyerId: 'u_rev1', rating: 5, ts: now - 60 * day,
        body: 'Pack arrived with the actual capacity printout — tested 17.6Ah on my own analyzer. This is how you sell batteries.' },
      { id: 'r2', orderId: 'o_9002', sellerId: 's_packworks', buyerId: 'u_rev2', rating: 5, ts: now - 33 * day,
        body: 'Second pack from PackWorks. Communication was fast, shipping was fast, cells are genuine.' },
      { id: 'r3', orderId: 'o_9003', sellerId: 's_packworks', buyerId: 'u_buyer', rating: 4, ts: now - 14 * day,
        body: 'Great battery, took a day longer than quoted to ship. Would buy again.' },
      { id: 'r4', orderId: 'o_9004', sellerId: 's_voltgarage', buyerId: 'u_rev2', rating: 5, ts: now - 90 * day,
        body: 'BBSHD kit had every cable labeled. Sam answered a connector question at 9pm. Legend.' },
      { id: 'r5', orderId: 'o_9005', sellerId: 's_voltgarage', buyerId: 'u_rev1', rating: 5, ts: now - 45 * day,
        body: 'Used hub motor was exactly as photographed, bearings feel new. Honest seller.' },
      { id: 'r6', orderId: 'o_9006', sellerId: 's_voltgarage', buyerId: 'u_buyer', rating: 4, ts: now - 12 * day,
        body: 'Controller works great. Manual is chinglish but the seller\'s wiring diagram saved me.' },
      { id: 'r7', orderId: 'o_9007', sellerId: 's_brakelab', buyerId: 'u_rev1', rating: 5, ts: now - 70 * day,
        body: 'Pre-bled and cut to length as promised. Bolted on in 40 minutes, no bleed needed.' },
      { id: 'r8', orderId: 'o_9008', sellerId: 's_brakelab', buyerId: 'u_rev2', rating: 4, ts: now - 28 * day,
        body: 'Rotors run true. One mounting bolt head was slightly rounded, minor gripe.' },
      { id: 'r9', orderId: 'o_9009', sellerId: 's_radspares', buyerId: 'u_rev2', rating: 5, ts: now - 50 * day,
        body: 'Takeoff battery plate came with both keys as listed. Photos matched exactly.' },
      { id: 'r10', orderId: 'o_9010', sellerId: 's_radspares', buyerId: 'u_rev1', rating: 4, ts: now - 22 * day,
        body: 'Tire showed up fast. Box was crushed but contents fine.' },
      { id: 'r11', orderId: 'o_9011', sellerId: 's_scootcity', buyerId: 'u_buyer', rating: 5, ts: now - 40 * day,
        body: 'Fender fit my G2 perfectly, OEM part as described. Same-day ship is real.' },
      { id: 'r12', orderId: 'o_9012', sellerId: 's_scootcity', buyerId: 'u_rev2', rating: 4, ts: now - 17 * day,
        body: 'Brake lever plug-and-play on my KQi3 Pro. Docked a star for thin packaging.' },
      { id: 'r13', orderId: 'o_9013', sellerId: 's_trailvolt', buyerId: 'u_rev1', rating: 4, ts: now - 30 * day,
        body: 'Used derailleur graded honestly. It really is basically new.' },
      { id: 'r14', orderId: 'o_9014', sellerId: 's_trailvolt', buyerId: 'u_rev2', rating: 3, ts: now - 8 * day,
        body: 'Wheel is true as promised but took 6 days to ship and tracking came late. Fine, not great.' },
    ],
    reports: [
      { id: 'rp1', sellerId: 's_trailvolt', reporterId: 'u_rev2', reason: 'not_shipped', status: 'resolved', ts: now - 26 * day, resolvedTs: now - 23 * day,
        details: 'Order sat for a week with no tracking.', resolution: 'Seller shipped after outreach; warned about handling-time policy. Buyer received item.' },
      { id: 'rp2', sellerId: 's_trailvolt', reporterId: 'u_rev1', reason: 'other', status: 'open', ts: now - 2 * day, resolvedTs: null,
        details: 'The for-parts frame listing photos don\'t clearly show the crack mentioned in specs. Feels under-disclosed.', resolution: null },
    ],
    applications: [
      { id: 'a1', userId: 'u_rev2', shop: "MotorMike's", slug: 'motormikes', status: 'pending', ts: now - 1 * day,
        pitch: 'I rebuild and resell hub motors from insurance-totaled e-bikes. 200+ eBay sales at 100% feedback, want a real storefront.' },
    ],
    recent: [],
  };
}

const LEGAL = {
  tos: { title: 'Terms of Service', body: `
<h3>1. What VoltHub is</h3><p>VoltHub is a marketplace venue. Sellers list and sell their own items; the contract of sale is between buyer and seller. VoltHub provides listing tools, discovery, and payment processing (via Stripe in the real product; simulated in this demo).</p>
<h3>2. Accounts</h3><p>You must be 18+ to buy or sell. You are responsible for activity on your account. We may suspend accounts that violate these terms or our policies.</p>
<h3>3. Fees</h3><p>Listing is free. VoltHub charges sellers 10% of the item subtotal (after seller discounts), minimum $0.50 per order. Payment processing is included.</p>
<h3>4. Content & conduct</h3><p>You own your listings; you grant VoltHub a license to display them. No fake reviews, no report abuse, no off-platform payment steering.</p>
<h3>5. Liability</h3><p>Items are sold by sellers, not VoltHub. To the extent permitted by law, VoltHub's liability is limited to fees paid to us in the prior 12 months. Disputes go through binding arbitration except where prohibited.</p>
<p><em>Demo document — real product ships lawyer-reviewed terms.</em></p>` },
  privacy: { title: 'Privacy Policy', body: `
<h3>What we collect</h3><p>Account info (name, email), listings, orders and shipping addresses, and usage analytics. In this demo, everything lives in your own browser's localStorage — nothing is sent anywhere.</p>
<h3>Processors (production)</h3><p>Supabase (database/auth), Stripe (payments — we never see card numbers), Resend (email), Vercel (hosting/analytics).</p>
<h3>Your rights</h3><p>Export or delete your data any time by emailing privacy@volthub.example. We honor GDPR/CCPA requests. Order records are retained 7 years for tax compliance.</p>
<h3>Cookies</h3><p>Session cookies for login; no third-party ad trackers, ever.</p>` },
  prohibited: { title: 'Prohibited & Restricted Items', body: `
<h3>Batteries (restricted)</h3><ul><li>Packs must be UN38.3 tested; UL 2271/2849 listing must be declared in the listing's certification field.</li><li>Ship per DOT/PHMSA rules — ground only where required, proper hazmat marking.</li><li>No damaged, swollen, water-exposed, or recalled packs. No repacked cells sold as OEM.</li></ul>
<h3>Prohibited outright</h3><ul><li>Stolen goods — serial numbers may be requested; we cooperate with law enforcement.</li><li>Devices marketed to defeat street-legality (speed-limit defeat dongles marketed for road use).</li><li>Counterfeit branded parts, items violating IP, recalled items (CPSC).</li></ul>
<h3>Condition honesty</h3><p>"For parts" items must state why. Undisclosed damage = listing removal on first offense, suspension on second.</p>` },
  refunds: { title: 'Returns, Refunds & Buyer Protection', body: `
<h3>The window</h3><p>You have 48 hours after delivery to inspect and open a dispute if the item is not as described. Items-not-received qualifies automatically when tracking shows no movement for 10 days.</p>
<h3>How disputes work</h3><p>Open a refund request from your order. VoltHub mediates between you and the seller within 3 business days. If found in your favor, the refund is issued to your original payment method and reversed from the seller's payout.</p>
<h3>What's covered</h3><p>Item not received, materially not as described, wrong item. Not covered: buyer's remorse, fitment mistakes when the listing's fitment data was accurate (check twice!), normal wear on used items graded correctly.</p>
<h3>Seller protections</h3><p>Sellers with tracking + accurate condition grading win not-as-described claims backed by their listing photos.</p>` },
};
